<!-- 
     Name of Page: OrderHeaderDetail view

     Method: this view for OrderHeaderDetail in the view mode

     Date created: autogenerated

     Use: this view used for view mode. Renders all ui interface including Detail actions but only in the view mode

     Input parameters:
     $ascope: common information object
     $data : model

     Output parameters:
     html
     
     Called from:
     Grid Controller

     Calls:
     model

     Last Modified: 20/02/2019
     Last Modified by: Zaharov Nikita
-->
<?php

    function renderRow($translation, $data, $fieldsDefinition, $values, $key, $value){
	echo "<tr><td class=\"title\">" . $translation->translateLabel(key_exists($key, $data->columnNames) ? $data->columnNames[$key] : $key) . "</td><td>";
	echo formatValue($data, $fieldsDefinition, $values, $key, $value);
	echo "</td></tr>";
    }

    function makeTableItems($values, $fieldsDefinition){
	$leftItems = [];
	$rightItems = [];
	
	$itemsHalf = 0;
	$itemsCount = 0;
	foreach($values as $key =>$value){
	    if(key_exists($key, $fieldsDefinition))
		$itemsCount++;
	}
	$itemsHalf = $itemsCount/2;

	$itemsCount = 0;
	foreach($values as $key =>$value){
	    if(key_exists($key, $fieldsDefinition)){
		if($itemsCount < $itemsHalf)
		    $leftItems[$key] = $value;
		else 
		    $rightItems[$key] = $value;
		$itemsCount++;
	    }
	}
	return [
	    "leftItems" => $leftItems,
	    "rightItems" => $rightItems
	];
    }
?>

<div id="row_viewer" class="row">
    <div class="order-entry-header">
	<?php
	    $headerItem = $data->getEditItem($ascope["item"], "...fields");
	?>
	<table class="col-md-12 col-xs-12 table">
	    <tbody>
		<tr class="row-header">
		    <?php foreach($data->headTableOne as $key=>$value): ?>
			<td>
			    <?php echo $translation->translateLabel($key); ?>   
			</td>
		    <?php endforeach; ?>
		</tr>
		<tr>
		    <?php foreach($data->headTableOne as $key=>$value): ?>
			<td>
			    <?php echo formatValue($data, $data->editCategories['...fields'], $headerItem, $value, $headerItem[$value]); ?>
			</td>
		    <?php endforeach; ?>
		</tr>
	    </tbody>
	</table>
	<?php if(property_exists($data, "headTableTwo")): ?>
	    <table class="col-md-12 col-xs-12 table">
		<tbody>
		    <tr class="row-header">
			<?php foreach($data->headTableTwo as $key=>$value): ?>
			    <td>
				<?php echo $translation->translateLabel($key); ?>   
			    </td>
			<?php endforeach; ?>
		    </tr>
		    <tr>
			<?php foreach($data->headTableTwo as $key=>$value): ?>
			    <td>
				<?php echo formatValue($data, $data->editCategories['...fields'], $headerItem, $value, $headerItem[$value]); ?>
			    </td>
			<?php endforeach; ?>
		    </tr>
		</tbody>
	    </table>
	<?php endif; ?>
    </div>
    
    <?php if(key_exists("Main", $data->editCategories) && !property_exists($data, "makeTabs")): ?>
	<ul class="nav nav-pills" role="tablist">
	    <?php
		//render tabs like Main, Current etc
		//uses $data(charOfAccounts model) as dictionaries which contains list of tab names
		foreach($data->editCategories as $key =>$value)
		if($key != '...fields') //making tab links only for usual categories, not for ...fields, reserved only for the data
		    echo "<li role=\"presentation\"". ( $ascope["category"] == $key ? " class=\"active\"" : "")  ."><a href=\"#". makeId($key) . "\" aria-controls=\"" . makeId($key) . "\" role=\"tab\" data-toggle=\"tab\">" . $translation->translateLabel($key) . "</a></li>";
	    ?>
	</ul>
	<br/>
	<!-- renders tables, contains record data using getEditItem from model  -->
	<div class="tab-content">
	    <?php foreach($data->editCategories as $key =>$value):  ?>
		<div role="tabpanel" class="tab-pane <?php echo $ascope["category"] == $key ? "active" : ""; ?>" id="<?php echo makeId($key); ?>">
		    <?php
			if($key == "Customer"){
			    $customerInfo = $data->getCustomerInfo($headerItem[property_exists($data, "customerField") ? $data->customerField : "CustomerID"]);
			    if($customerInfo != null){
				$tableItems = makeTableItems($customerInfo, $data->customerFields);
				$tableCategories = $data->customerFields;
				$items = $customerInfo;
			    }
                	}else if($key == "Vendor"){
			    $vendorInfo = $data->getVendorInfo($headerItem[property_exists($data, "vendorField") ? $data->vendorField : "VendorID"]);
			    if($vendorInfo != null){
				$tableItems = makeTableItems($vendorInfo, $data->vendorFields);
				$tableCategories = $data->vendorFields;
				$items = $vendorInfo;
			    }
			}
			else {
			    $item = $data->getEditItem($ascope["item"], $key);
			    $tableCategories = $data->editCategories[$key];
			    $tableItems = makeTableItems($item, $tableCategories);
			    $items = $item;
			}
		    ?>
		    <div class="table-responsive col-md-12 col-xs-12 row">
			<div class=" col-md-5 col-xs-5">
			    <table class="table table-bordered order-entry-main-table ">
				<tbody id="row_viewer_tbody">
				    <?php 
					foreach($tableItems["leftItems"] as $key =>$value)
					renderRow($translation, $data, $tableCategories, $items, $key, $value);
				    ?>
				</tbody>
			    </table>
			</div>
			<div class="col-md-5 col-xs-5">
			    <table class="table table-bordered order-entry-main-table">
				<tbody id="row_viewer_tbody">
				    <?php 
					foreach($tableItems["rightItems"] as $key =>$value)
					renderRow($translation, $data, $tableCategories,  $items,$key, $value);
				    ?>
				</tbody>
			    </table>
			</div>
		    </div>
		</div>
	    <?php endforeach; ?>
	</div>
    <?php endif; ?>
    
    <?php if(property_exists($data, "headTableThree")): ?>
	<div class="order-entry-header col-md-12 col-xs-12">
	    <table class="table">
		<tbody>
		    <tr class="row-header">
			<?php foreach($data->headTableThree as $key=>$value): ?>
			    <td>
				<?php echo $translation->translateLabel($key); ?>   
			    </td>
			<?php endforeach; ?>
		    </tr>
		    <tr>
			<?php foreach($data->headTableThree as $key=>$value): ?>
			    <td>
				<?php echo formatValue($data, $data->editCategories['...fields'], $headerItem, $value, $headerItem[$value]); ?>
			    </td>
			<?php endforeach; ?>
		    </tr>
		</tbody>
	    </table>
	</div>
    <?php endif; ?>

    <!-- Detail table -->
    <?php
	if(property_exists($data, "detailTable"))
    	    require __DIR__ . "/components/detailGrid.php";
    ?>

    <!-- footer table -->
    <?php if(property_exists($data, "footerTable")): ?>
	<div class="panel panel-default order-entry-header col-md-8 col-xs-12" style="margin-top:20px;">
	    <table class="col-md-12 col-xs-12 order-entry-flagsanddates-table">
		<tbody>
		    <tr>
			<td>
			    <?php
				foreach($data->footerTable["flagsHeader"] as $key=>$value){
				    formatValue($data, $data->editCategories['...fields'], $headerItem, $value, $headerItem[$value]);
				    echo $translation->translateLabel($key);
				}			    
			    ?>
			</td>
			<td>
			</td>
		    </tr>
		    <?php foreach($data->footerTable["flags"] as $row): ?>
			<tr>
			    <td>
				<div><?php echo formatValue($data, $data->editCategories['...fields'], $headerItem, $row[0], $headerItem[$row[0]]); ?><?php echo $translation->translateLabel($row[1]); ?></div>
			    </td>
			    <td class="date-title">
				<?php if(count($row) > 2): ?>
				    <div class="pull-right"><b><?php echo $translation->translateLabel($row[3]); ?>: </b></div>
				<?php endif; ?>
			    </td>
			    <td>
				<?php if(count($row) > 2): ?>
				    <?php echo formatValue($data, $data->editCategories['...fields'], $headerItem, $row[2], $headerItem[$row[2]]); ?>
				<?php endif; ?>
			    </td>
			    <td>
				<?php if($row[0] == "Shipped"): ?>
				    <div><b><?php echo $translation->translateLabel("Trk #"); ?> </b><?php echo formatValue($data, $data->editCategories['...fields'], $headerItem, "TrackingNumber", $headerItem["TrackingNumber"]); ?></div>
				<?php elseif($row[0] == "Invoiced"): ?>
				    <div><b><?php echo $translation->translateLabel("Inv #"); ?> </b><?php echo formatValue($data, $data->editCategories['...fields'], $headerItem, "InvoiceNumber", $headerItem["InvoiceNumber"]); ?></div>
				<?php endif;  ?>
			    </td>
			</tr>
		    <?php endforeach; ?>
		</tbody>
	    </table>
	</div>
	<div class="order-entry-header col-md-4 col-xs-12" style="margin-top:20px;">
	    <table class="order-entry-balance-table col-md-12 col-xs-12">
		<tbody>
		    <?php foreach($data->footerTable["totalFields"] as $key=>$value): ?>
			<tr>
			    <td>
				<?php if($key == "Shipping"):?>
				    <div><?php echo formatValue($data, $data->editCategories['...fields'], $headerItem, "TaxFreight", $headerItem["TaxFreight"]); ?><?php echo $translation->translateLabel("Tax Freight"); ?></div>
				<?php endif; ?>
			    </td>
			    <td>
				<b><?php echo $translation->translateLabel($key); ?>: </b>
			    </td>
			    <td>
				<div class="pull-right"><?php echo formatValue($data, $data->editCategories['...fields'], $headerItem, $value, $headerItem[$value]); ?></div>
			    </td>
			</tr>
		    <?php endforeach; ?>
		</tbody>
	    </table>
	</div>
    <?php endif; ?>
    
    <?php
	if(file_exists(__DIR__ . "/../../../" . $PartsPath . "viewFooter.php"))
	    require __DIR__ . "/../../../" . $PartsPath . "viewFooter.php";
	if(file_exists(__DIR__ . "/../../../" . $PartsPath . "vieweditFooter.php"))
	    require __DIR__ . "/../../../" . $PartsPath . "vieweditFooter.php";
    ?>

    <div class="col-md-12 col-xs-12 row">
	<div style="margin-top:10px" class="pull-right">
	    <!--
		 buttons Edit and Cancel
		 for translation uses translation model
		 for category(which tab is activated) uses $ascope of controller
	    -->
	    <?php if($security->can("update")): ?>
		<a class="btn btn-info" href="<?php echo $linksMaker->makeGridItemEdit($ascope["path"], $ascope["item"]); ?>">
		    <?php echo $translation->translateLabel("Edit"); ?>
		</a>
		<?php
		    if(file_exists(__DIR__ . "/../../../" . $PartsPath . "viewActions.php"))
			require __DIR__ . "/../../../" . $PartsPath . "viewActions.php";
		    if(file_exists(__DIR__ . "/../../../" . $PartsPath . "vieweditActions.php"))
			require __DIR__ . "/../../../" . $PartsPath . "vieweditActions.php";
		?>
	    <?php endif; ?>
	    <a class="btn btn-info" href="<?php echo $linksMaker->makeGridItemViewCancel($ascope["path"]); ?>">
		<?php echo $translation->translateLabel("Exit"); ?>
	    </a>
	</div>
    </div>
</div>
