-- DDL script for table ErrorLogDetail for MySQL
-- Generated by (c) Ispirer SQLWays 4.0 Build 219 Licensed to STFB
-- Timestamp: Tue Jul 28 16:09:02 2015

-- Create table statement


CREATE TABLE ErrorLogDetail
(
   CompanyID NATIONAL VARCHAR(36) NOT NULL,
   DivisionID NATIONAL VARCHAR(36) NOT NULL,
   DepartmentID NATIONAL VARCHAR(36) NOT NULL,
   ErrorDetailID INT NOT NULL  AUTO_INCREMENT,
   ErrorID INT NOT NULL,
   ParameterName NATIONAL VARCHAR(50),
   ParameterValue NATIONAL VARCHAR(50),
   LockedBy NATIONAL VARCHAR(36),
   LockTS DATETIME,
   PRIMARY KEY(ErrorDetailID,CompanyID,DivisionID,DepartmentID)
)  AUTO_INCREMENT = 1;

