CREATE PROCEDURE PayrollEmployeesTaskDetailInsert (v_CompanyID NATIONAL VARCHAR(36),
v_DivisionID NATIONAL VARCHAR(36),
v_DepartmentID NATIONAL VARCHAR(36),
v_EmployeeID NATIONAL VARCHAR(36),
v_EmployeeTaskID NATIONAL VARCHAR(36),
v_TaskDetailDate DATETIME,
v_TaskDetailComplete BOOLEAN,
v_TaskDetailCompleteDate DATETIME,
v_TaskDetailRelatedDocumentType NATIONAL VARCHAR(36),
v_TaskDetailRelatedDocumentNumber NATIONAL VARCHAR(36),
v_TaskDetailDescription NATIONAL VARCHAR(200),
v_LockedBy NATIONAL VARCHAR(36),
v_LockTS DATETIME) begin
   INSERT INTO PayrollEmployeesTaskDetail(CompanyID,
DivisionID,
DepartmentID,
EmployeeID,
EmployeeTaskID,
TaskDetailRelatedDocumentType,
TaskDetailRelatedDocumentNumber,
TaskDetailDescription,
TaskDetailDate,
TaskDetailComplete,
TaskDetailCompleteDate,
LockedBy,
LockTS)
VALUES(v_CompanyID,
v_DivisionID,
v_DepartmentID,
v_EmployeeID,
v_EmployeeTaskID,
v_TaskDetailRelatedDocumentType,
v_TaskDetailRelatedDocumentNumber,
v_TaskDetailDescription,
v_TaskDetailDate,
v_TaskDetailComplete,
v_TaskDetailCompleteDate,
v_LockedBy,
v_LockTS);

   SELECT LAST_INSERT_ID();
end