* intro
  We have a directory structure for views and models most identical Enterprise Cloud version.
  For example: 
  General Ledger/Ledger/View GL Transactions grid view stored in 
  + Cloud version - EnterpriseASPGL/Ledger/LedgerTransactionsList.aspx
  + newtech - resources/views/EnterpriseASPGL/Ledger/LedgerTransactionsList.php
  + integralx - views/EnterpriseASPGL/Ledger/LedgerTransactionsList.php
  
  Simple screens, which do not have unique functions, just crud on some table, also do not have own view. It's using common
  view.
  
  General Ledger/Ledger/View GL Transactions model stored in 
  + newtech - app/Http/Models/EnterpriseASPGL/Ledger/LedgerTransactionsList.php
  + integralx - models/EnterpriseASPGL/Ledger/LedgerTransactionsList.php
  
  model contains 
  + table name
  + key fields
  + screen displayed title
  + grid fields
  + fields for working with in read, edit and new modes
  + columnname to translated name list

* structure of simple model screen on example laravel/app/Http/Models/EnterpriseASPSystem/LedgerSetup/LedgerTransactionsTypesList.php
<?php
namespace App\Models;
//loading parent class for model, which contains method for cread, read, update, delete data. 
require __DIR__ . "/../../../Models/gridDataSource.php";

class gridData extends gridDataSource{
    protected $tableName = "ledgertransactiontypes"; //name of table for work on
    public $dashboardTitle ="Ledger Transaction Types"; 
    public $breadCrumbTitle ="Ledger Transaction Types";
    public $idField ="TransactionTypeID";//this value not used anymore
    //list of key fields
    public $idFields = ["CompanyID","DivisionID","DepartmentID","TransactionTypeID"];

    /*
      list of fields, displayed in grid. field names same as in table column name. Also each field description has
          + dbType - type of data in table
	  + inputType - type, used for generating properly input or properly displayed value. For example:
	    dbType can be varchar(36) but inputType can be dropdown with dataProvider which load values for dropdown from another table.
	    or
	    dbType can be tinyint(1) but inputType can be checkbox what means in edit,view and new modes it will be displayed as checkbox and True or False in grid mode
      */
    public $gridFields = [
        "TransactionTypeID" => [
            "dbType" => "varchar(36)",
            "inputType" => "text"
        ],
        "TransactionTypeDescription" => [
            "dbType" => "varchar(80)",
            "inputType" => "text"
        ]
    ];

    /*
    list of fields united in categories(this contains only Main category and rendered as Main tab).
    format of field description same as above.
    All autogenerated models contains only one Main category and all fields(all table columns) inserted in it.
    If editCategories contains several categories, each displayed as tab
    */
    public $editCategories = [
        "Main" => [
            "TransactionTypeID" => [
                "dbType" => "varchar(36)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "TransactionTypeDescription" => [
                "dbType" => "varchar(80)",
                "inputType" => "text",
                "defaultValue" => ""
            ]
        ]
    ];
    /*
    array, contains fieldname and displayed field name
    displayed field name passed to translation
    In autogenerated models all fieldnames and displayed fieldnames is same except for fieldnames for grid.
    */
    public $columnNames = [
        "TransactionTypeID" => "Transaction Type ID",
        "TransactionTypeDescription" => "Transaction Type Description"
    ];
}
?>

* structure of more complicated model laravel/app/Http/Models/EnterpriseASPSystem/CompanySetup/AccessPermissionsList.php
  <?php
namespace App\Models;
require __DIR__ . "/../../../Models/gridDataSource.php";
class gridData extends gridDataSource{
    protected $tableName = "accesspermissions";//name of table for work on
    public $dashboardTitle ="Access Permissions";
    public $breadCrumbTitle ="Access Permissions";
    public $idField ="EmployeeID";//this value not used anymore
    //list of key fields
    public $idFields = ["CompanyID","DivisionID","DepartmentID","EmployeeID"];
    /*
      list of fields, displayed in grid. field names same as in table column name. Also each field description has
          + dbType - type of data in table
	  + inputType - type, used for generating properly input or properly displayed value. For example:
	    dbType can be varchar(36) but inputType can be dropdown with dataProvider which load values for dropdown from another table.
	    or
	    dbType can be tinyint(1) but inputType can be checkbox what means in edit,view and new modes it will be displayed as checkbox and True or False in grid mode
      */
    public $gridFields = [
        "EmployeeID" => [
            "dbType" => "varchar(36)",
            "inputType" => "text"
        ],
        "SecurityLevel" => [
            "dbType" => "smallint(6)",
            "inputType" => "text"
        ]
    ];

    /*
    list of fields united in categories(this contains only Main category and rendered as Main tab).
    format of field description same as above.
    All autogenerated models contains only one Main category and all fields(all table columns) inserted in it.
    Autogenerated AccessPermissionsList had only one category and all feilds was be in it. Fields was categorized by categories by hand.
    If editCategories contains several categories, each displayed as tab
    */
    public $editCategories = [
        "Main" => [
            "EmployeeID" => [
                "dbType" => "varchar(36)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "SecurityLevel" => [
                "dbType" => "smallint(6)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "MachineName" => [
                "dbType" => "varchar(50)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "IPAddress" => [
                "dbType" => "varchar(50)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "RestrictMultipleLogins" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "RestrictSecurityIP" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "DefaultPageToDisplay" => [
                "dbType" => "varchar(120)",
                "inputType" => "text",
                "defaultValue" => ""
            ]
        ],
        "Orders" => [
            "OEView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "OEAdd" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "OEEdit" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "OEDelete" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "OEReports" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ApproveOrders" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ]
        ],
        "Receivables" => [
            "ARView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ARAdd" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "AREdit" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ARDelete" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ARReports" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ApproveReceipt" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ApproveContract" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ApproveCustomer" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ApproveRMA" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ]
        ],
        "Purchase" => [
            "POView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "POAdd" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "POEdit" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "PODelete" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ApprovePurchase" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "POReports" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ]
        ],
        "Payables" => [
            "APView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "APAdd" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "APEdit" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "APDelete" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "APChecks" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "APReports" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ApproveVendor" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ApproveAPChedks" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ApprovePayment" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ApproveReturns" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ]
        ],
        "Ledger" => [
            "GLView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "GLAdd" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "GLEdit" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "GLDelete" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "GLReports" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "GLFinancials" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "GLMonthEnd" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "GLYearEnd" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ]
        ],
        "Inventory" => [
            "WHAdjust" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "WHTransfer" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "WHPick" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "WHPack" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "WHShip" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "WHReceive" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "WHPrint" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "WOView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "WOAdd" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "WOEdit" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "WODelete" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "WOReports" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "WOForecast" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ApproveAdjustment" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ApproveTransfer" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ApproveItems" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ]
        ],
        "Employee" => [
            "EMView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "EMAdd" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "EMEdit" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "EMDelete" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "EMReports" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ApproveEmployees" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ]
        ],
        "Payroll" => [
            "PRView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "PRAdd" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "PREdit" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "PRDelete" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "PRReports" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "PRChecks" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ApprovePayroll" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ]
        ],
        "MainTabs" => [
            "MTARView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "MTAPView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "MTGLView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "MTInventoryView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "MTMRPView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "MTFundView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "MTCRMView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "MTPayrollView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "MTSystemView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "MTReportsView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ]            
        ],
        "ReportTabs" => [
            "RTFinancialView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "RTARView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "RTAPView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "RTGLView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "RTInventoryView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "RTCRMView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "RTPayrollView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ]
        ],
        "Admin" => [
            "ADView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ADSecurity" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ADSetup" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "APSetup" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ARSetup" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "AuditSetup" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ChallangeSetup" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "EMSetup" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "GLSetup" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "OESetup" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "POSetup" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "PRSetup" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "WHSetup" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "WOSetup" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "AuditView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "AuditAdd" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "AuditEdit" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "AuditDelete" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "AuditReports" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ChallangeView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ChallangeAdd" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ChallangeEdit" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ChallangeDelete" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ChallangeReports" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ApproveLowMargins" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "RTSystemView" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ]
        ]
    ];
    public $columnNames = [
        "EmployeeID" => "Employee ID",
        "SecurityLevel" => "Security Level",
        "DefaultPageToDisplay" => "Default Page To Display",
        "MachineName" => "Machine Name",
        "RestrictMultipleLogins" => "Restrict Multiple Logins",
        "IPAddress" => "IP Address",
        "RestrictSecurityIP" => "Restrict Security IP",
        "OEView" => "OE View",
        "OEAdd" => "OE Add",
        "OEEdit" => "OE Edit",
        "OEDelete" => "OE Delete",
        "OEReports" => "OE Reports",
        "OESetup" => "OE Setup",
        "ARView" => "AR View",
        "ARAdd" => "AR Add",
        "AREdit" => "AR Edit",
        "ARDelete" => "AR Delete",
        "ARReports" => "AR Reports",
        "ARSetup" => "AR Setup",
        "POView" => "PO View",
        "POAdd" => "PO Add",
        "POEdit" => "PO Edit",
        "PODelete" => "PO Delete",
        "POReports" => "PO Reports",
        "POSetup" => "PO Setup",
        "APView" => "AP View",
        "APAdd" => "AP Add",
        "APEdit" => "AP Edit",
        "APDelete" => "AP Delete",
        "APChecks" => "AP Checks",
        "APReports" => "AP Reports",
        "APSetup" => "AP Setup",
        "GLView" => "GL View",
        "GLAdd" => "GL Add",
        "GLEdit" => "GL Edit",
        "GLDelete" => "GL Delete",
        "GLReports" => "GL Reports",
        "GLFinancials" => "GL Financials",
        "GLMonthEnd" => "GL Month End",
        "GLYearEnd" => "GL Year End",
        "GLSetup" => "GL Setup",
        "EMView" => "EM View",
        "EMAdd" => "EM Add",
        "EMEdit" => "EM Edit",
        "EMDelete" => "EM Delete",
        "EMReports" => "EM Reports",
        "EMSetup" => "EM Setup",
        "PRView" => "PR View",
        "PRAdd" => "PR Add",
        "PREdit" => "PR Edit",
        "PRDelete" => "PR Delete",
        "PRChecks" => "PR Checks",
        "PRReports" => "PR Reports",
        "PRSetup" => "PR Setup",
        "WHPick" => "WHPick",
        "WHPack" => "WHPack",
        "WHShip" => "WHShip",
        "WHPrint" => "WHPrint",
        "WHReceive" => "WHReceive",
        "WHTransfer" => "WHTransfer",
        "WHAdjust" => "WHAdjust",
        "WHSetup" => "WH Setup",
        "WOView" => "WOView",
        "WOAdd" => "WOAdd",
        "WOEdit" => "WOEdit",
        "WODelete" => "WODelete",
        "WOReports" => "WOReports",
        "WOForecast" => "WOForecast",
        "WOSetup" => "WO Setup",
        "ADView" => "AD View",
        "ADSetup" => "AD Setup",
        "ADSecurity" => "AD Security",
        "ChallangeView" => "Challange View",
        "ChallangeAdd" => "Challange Add",
        "ChallangeEdit" => "Challange Edit",
        "ChallangeDelete" => "Challange Delete",
        "ChallangeReports" => "Challange Reports",
        "ChallangeSetup" => "Challange Setup",
        "AuditView" => "Audit View",
        "AuditAdd" => "Audit Add",
        "AuditEdit" => "Audit Edit",
        "AuditDelete" => "Audit Delete",
        "AuditReports" => "Audit Reports",
        "AuditSetup" => "Audit Setup",
        "ApproveCustomer" => "Approve Customer",
        "ApproveVendor" => "Approve Vendor",
        "ApprovePayment" => "Approve Payment",
        "ApprovePurchase" => "Approve Purchase",
        "ApproveTransfer" => "Approve Transfer",
        "ApproveAdjustment" => "Approve Adjustment",
        "ApproveReceipt" => "Approve Receipt",
        "ApprovePayroll" => "Approve Payroll",
        "ApproveAPChedks" => "Approve APChedks",
        "ApproveEmployees" => "Approve Employees",
        "ApproveItems" => "Approve Items",
        "ApproveLowMargins" => "Approve Low Margins",
        "ApproveOrders" => "Approve Orders",
        "ApproveContract" => "Approve Contract",
        "ApproveReturns" => "Approve Returns",
        "ApproveRMA" => "Approve RMA",
        "MTARView" => "MTAR View",
        "MTAPView" => "MTAP View",
        "MTGLView" => "MTGL View",
        "MTInventoryView" => "MTInventory View",
        "MTMRPView" => "MTMRP View",
        "MTFundView" => "MTFund View",
        "MTCRMView" => "MTCRM View",
        "MTPayrollView" => "MTPayroll View",
        "MTSystemView" => "MTSystem View",
        "MTReportsView" => "MTReports View",
        "RTFinancialView" => "RTFinancial View",
        "RTARView" => "RTAR View",
        "RTAPView" => "RTAP View",
        "RTGLView" => "RTGL View",
        "RTInventoryView" => "RTInventory View",
        "RTCRMView" => "RTCRM View",
        "RTPayrollView" => "RTPayroll View",
        "RTSystemView" => "RTSystem View"
    ];
}
?>

* what need to do with autogenerated simple screen
 + correct dashboard name and crumboard name if it need(for properly translation and displaying). In most cases this titles is already good.
 + categorize fields in editCategories by categories. Divert fields Main on Main,SomethingElse,SomethingElse2 etc if it need
 + corrent right side values in columnNames for properly translating

* about ide, code style, indenting
  I'm using emacs(it is customizable editor), but i do not advise him. It's pretty complicated editor and very adapted for working without mice(or touchpad) in
  most cases. I recomended simple editor like Notepad++ or full feature ide like NetBeans.
