update databaseinfo set value='2019_06_13',lastupdate=now() WHERE id='Version';

DROP TABLE IF EXISTS `purchasecontractdetail`;
CREATE TABLE `purchasecontractdetail` (
  `CompanyID` varchar(36) NOT NULL,
  `DivisionID` varchar(36) NOT NULL,
  `DepartmentID` varchar(36) NOT NULL,
  `PurchaseContractNumber` varchar(36) NOT NULL,
  `PurchaseContractLineNumber` bigint(20) NOT NULL AUTO_INCREMENT,
   `ItemID` varchar(36) DEFAULT NULL,
  `VendorItemID` varchar(36) DEFAULT NULL,
  `Description` varchar(80) DEFAULT NULL,
  `WarehouseID` varchar(36) DEFAULT 'DEFAULT',
  `WarehouseBinID` varchar(36) DEFAULT NULL,
  `SerialNumber` varchar(50) DEFAULT NULL,
  `OrderQty` float DEFAULT '0',
  `ItemUOM` varchar(15) DEFAULT 'Each',
  `ItemWeight` float DEFAULT '0',
  `DiscountPerc` float DEFAULT '0',
  `Taxable` tinyint(1) DEFAULT '0',
  `ItemCost` decimal(19,4) DEFAULT '0.0000',
  `CurrencyID` varchar(3) DEFAULT NULL,
  `CurrencyExchangeRate` float DEFAULT NULL,
  `ItemUnitPrice` decimal(19,4) DEFAULT '0.0000',
  `TaxGroupID` varchar(36) DEFAULT NULL,
  `TaxAmount` decimal(19,4) DEFAULT NULL,
  `TaxPercent` float DEFAULT NULL,
  `SubTotal` decimal(19,4) DEFAULT NULL,
  `Total` decimal(19,4) DEFAULT '0.0000',
  `TotalWeight` float DEFAULT '0',
  `GLPurchaseAccount` varchar(36) DEFAULT '131000',
  `ProjectID` varchar(36) DEFAULT 'DEFAULT',
  `Received` tinyint(1) DEFAULT '0',
  `ReceivedDate` datetime DEFAULT '1000-01-01',
  `ReceivedQty` float DEFAULT '0',
  `RecivingNumber` varchar(36) DEFAULT NULL,
  `TrackingNumber` varchar(50) DEFAULT NULL,
  `DetailMemo1` varchar(50) DEFAULT NULL,
  `DetailMemo2` varchar(50) DEFAULT NULL,
  `DetailMemo3` varchar(50) DEFAULT NULL,
  `DetailMemo4` varchar(50) DEFAULT NULL,
  `DetailMemo5` varchar(50) DEFAULT NULL,
  `GLControlNumber` varchar(36) DEFAULT NULL,
  `LockedBy` varchar(36) DEFAULT NULL,
  `LockTS` datetime DEFAULT NULL,
  PRIMARY KEY (`PurchaseContractLineNumber`,`CompanyID`,`DivisionID`,`DepartmentID`,`PurchaseContractNumber`)
) ENGINE=InnoDB AUTO_INCREMENT=81 DEFAULT CHARSET=utf8;
