<?php
/*
  Name of Page: Purchase Contract Detail model
   
  Method: Model for gridView It provides data from database and default values, column names and categories
   
  Date created: 13/06/2019 Nikita Zaharov
   
  Use: this model used by views/PurchaseContractDetail for:
  - as a dictionary for view during building interface(tabs and them names, fields and them names etc, column name and corresponding translationid)
  - for loading data from tables, updating, inserting and deleting
   
  Input parameters:
  $db: database instance
  methods have their own parameters
   
  Output parameters:
  - dictionaries as public properties
  - methods have their own output
   
  Called from:
  created and used for ajax requests by controllers
  used as model by views/gridView
   
  Calls:
  MySql Database
   
  Last Modified: 13/06/2019
  Last Modified by Nikita Zaharov
*/

require "./models/helpers/recalc.php";
require "./models/gridDataSource.php";

class PurchaseContractDetail extends gridDataSource{
    public $tableName = "purchasecontractdetail";
    public $parentTableName = "purchasecontractheader";
    public $dashboardTitle ="Purchase ContractDetail";
    public $breadCrumbTitle ="Purchase Contract Detail";
    public $idField ="PurchaseContractNumber";
    public $idFields = ["CompanyID","DivisionID","DepartmentID","PurchaseContractNumber", "PurchaseContractLineNumber"];
    public $gridFields = [
        "ItemID" => [
            "dbType" => "varchar(36)",
            "inputType" => "text",
            "defaultValue" => ""
        ],
        "VendorItemID" => [
            "dbType" => "varchar(36)",
            "inputType" => "text",
            "defaultValue" => ""
        ],
        "Description" => [
            "dbType" => "varchar(80)",
            "inputType" => "text",
            "defaultValue" => ""
        ],
        "OrderQty" => [
            "dbType" => "float",
            "inputType" => "text",
            "defaultValue" => ""
        ],
        "ItemUOM" => [
            "dbType" => "varchar(15)",
            "inputType" => "text",
            "defaultValue" => ""
        ],
        "ItemUnitPrice" => [
            "dbType" => "decimal(19,4)",
            "inputType" => "text",
            "defaultValue" => ""
        ],
        "CurrencyID" => [
            "dbType" => "varchar(3)",
            "inputType" => "text",
            "defaultValue" => ""
        ],
        "Total" => [
            "dbType" => "decimal(19,4)",
            "inputType" => "text",
            "defaultValue" => ""
        ],
        "GLPurchaseAccount" => [
            "dbType" => "varchar(36)",
            "inputType" => "text",
            "defaultValue" => ""
        ],
        "ProjectID" => [
            "dbType" => "varchar(36)",
            "inputType" => "text",
            "defaultValue" => ""
        ]
    ];

    public $editCategories = [
        "Main" => [
            "PurchaseContractNumber" => [
                "dbType" => "varchar(36)",
                "disabledEdit" => "true",
                "disabledNew" => "true",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "PurchaseContractLineNumber" => [
                "dbType" => "bigint(20)",
                "inputType" => "text",
                "disabledEdit" => "true",
                "autogenerated" => true,
                "disabledNew" => "true",
                "defaultOverride" => true,
                "defaultValue" => "(new)"
            ],
            "ItemID" => [
                "dbType" => "varchar(36)",
                "inputType" => "dialogChooser",
                "dataProvider" => "getItems",
                "defaultValue" => ""
            ],
            "VendorItemID" => [
                "dbType" => "varchar(36)",
                "inputType" => "text",
                //"inputType" => "dialogChooser",
                //"dataProvider" => "getItems",
                "defaultValue" => ""
            ],
            "Description" => [
                "dbType" => "varchar(80)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "WarehouseID" => [
                "dbType" => "varchar(36)",
                "inputType" => "dropdown",
                "dataProvider" => "getWarehouses",
                "defaultValue" => ""
            ],
            "WarehouseBinID" => [
                "dbType" => "varchar(36)",
                "inputType" => "dropdown",
                "depends" => [
                    "WarehouseID" => "WarehouseID"
                ],
                "dataProvider" => "getWarehouseBins",
                "defaultValue" => ""
            ],
            "SerialNumber" => [
                "dbType" => "varchar(50)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "OrderQty" => [
                "dbType" => "float",
                "inputType" => "text",
                "onchange" => "recalcDetailClient",
                "defaultValue" => ""
            ],
            "ItemUOM" => [
                "dbType" => "varchar(15)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "ItemWeight" => [
                "dbType" => "float",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "DiscountPerc" => [
                "dbType" => "float",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "Taxable" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ItemCost" => [
                "dbType" => "decimal(19,4)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "CurrencyID" => [
                "dbType" => "varchar(3)",
                "inputType" => "dropdown",
                "defaultValue" => "USD",
                "dataProvider" => "getCurrencyTypes"
            ],
            "CurrencyExchangeRate" => [
                "dbType" => "float",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "ItemUnitPrice" => [
                "dbType" => "decimal(19,4)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "TaxGroupID" => [
                "dbType" => "varchar(36)",
                "inputType" => "dropdown",
                "dataProvider" => "getTaxGroups",
                "defaultValue" => ""
            ],
            "TaxAmount" => [
                "dbType" => "decimal(19,4)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "TaxPercent" => [
                "dbType" => "float",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "SubTotal" => [
                "dbType" => "decimal(19,4)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "Total" => [
                "dbType" => "decimal(19,4)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "TotalWeight" => [
                "dbType" => "float",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "GLPurchaseAccount" => [
                "dbType" => "varchar(36)",
                "inputType" => "dropdown",
                "dataProvider" => "getAccounts",
                "defaultValue" => ""
            ],
            "ProjectID" => [
                "dbType" => "varchar(36)",
                "inputType" => "dropdown",
                "dataProvider" => "getProjects",
                "defaultValue" => ""
            ],
            "Received" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "ReceivedDate" => [
                "dbType" => "datetime",
                "inputType" => "datetime",
                "defaultValue" => "now"
            ],
            "ReceivedQty" => [
                "dbType" => "float",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "RecivingNumber" => [
                "dbType" => "varchar(36)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "TrackingNumber" => [
                "dbType" => "varchar(50)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "GLControlNumber" => [
                "dbType" => "varchar(36)",
                "inputType" => "text",
                "defaultValue" => ""
            ]
        ],
        "Memos" => [
            "DetailMemo1" => [
                "dbType" => "varchar(50)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "DetailMemo2" => [
                "dbType" => "varchar(50)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "DetailMemo3" => [
                "dbType" => "varchar(50)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "DetailMemo4" => [
                "dbType" => "varchar(50)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "DetailMemo5" => [
                "dbType" => "varchar(50)",
                "inputType" => "text",
                "defaultValue" => ""
            ]
        ]
    ];
    
    public $columnNames = [
        "PurchaseContractNumber" => "Purchase Contract Number",
        "ItemID" => "Item ID",
        "VendorItemID" => "Vendor Item ID",
        "Description" => "Description",
        "WarehouseID" => "Warehouse ID",
        "WarehouseBinID" => "Warehouse Bin ID",
        "SerialNumber" => "Serial Number",
        "OrderQty" => "Order Qty",
        "ItemUOM" => "Item UOM",
        "ItemWeight" => "ItemWeight",
        "DiscountPerc" => "Discount Perc",
        "Taxable" => "Taxable",
        "ItemCost" => "Item Cost",
        "CurrencyID" => "Currency ID",
        "CurrencyExchangeRate" => "Currency Exchange Rate",
        "ItemUnitPrice" => "Item Unit Price",
        "TaxGroupID" => "Tax Group ID",
        "TaxAmount" => "Tax Amount",
        "TaxPercent" => "Tax Percent",
        "SubTotal" => "Sub Total",
        "Total" => "Total",
        "TotalWeight" => "Total Weight",
        "GLPurchaseAccount" => "GL Purchase Account",
        "ProjectID" => "Project ID",
        "Received" => "Received",
        "ReceivedDate" => "Received Date",
        "ReceivedQty" => "Received Qty",
        "RecivingNumber" => "Reciving Number",
        "TrackingNumber" => "Tracking Number",
        "DetailMemo1" => "Memo 1",
        "DetailMemo2" => "Memo 2",
        "DetailMemo3" => "Memo 3",
        "DetailMemo4" => "Memo 4",
        "DetailMemo5" => "Memo 5",
        "GLControlNumber" => "GL Control Number",
        "PurchaseContractLineNumber" => "Purchase Contract Line Number"
    ];

    public function recalcForClient(){
        $user = Session::get("user");

        $recalc = new recalcHelper;
        
        $header = DB::select("select * from purchasecontractheader WHERE CompanyID=? AND DivisionID=? AND DepartmentID=? AND PurchaseContractNumber", [$user["CompanyID"], $user["DivisionID"], $user["DepartmentID"], $_POST["PurchaseContractNumber"]])[0];
        $Precision = $recalc->getPrecision($header->CurrencyID);

        foreach($_POST as &$field)
            $field = str_replace(",", "", $field);
        
        $detailResult = $recalc->recalcPurchaseContractDetail($Precision, (object)$_POST);

        echo json_encode($detailResult, JSON_PRETTY_PRINT);
    }
}
?>
