<?php
/*
  Name of Page: InventoryWorkOrderDetail model

  Method: Model for grid view. It provides data from database and default values, column names and categories

  Date created: autogenerated

  Use: this model used by gird views
  - as a dictionary for view during building interface(tabs and them names, fields and them names etc, column name and corresponding translationid)
  - for loading data from tables, updating, inserting and deleting
   
  Input parameters:
  $db: database instance
  methods have their own parameters

  Output parameters:
  - dictionaries as public properties
  - methods have their own output

  Called from:
  created and used for ajax requests by grid controller
  used as model by grid view

  Calls:
  MySql Database

  Last Modified: 08/15/2017
  Last Modified by: Nikita Zaharov
*/

require "./models/gridDataSource.php";

class gridData extends gridDataSource{
    protected $tableName = "workorderdetail";
    public $dashboardTitle ="Inventory Work Order Detail";
    public $breadCrumbTitle ="Inventory Work Order Detail";
    public $idField ="WorkOrderNumber";
    public $idFields = ["CompanyID","DivisionID","DepartmentID","WorkOrderNumber", "WorkOrderLineNumber"];
    public $gridFields = [
        "WorkOrderNumber" => [
            "dbType" => "varchar(36)",
            "inputType" => "text",
            "disabledEdit" => "true"
        ],
        "WorkOrderLineNumber" => [
            "dbType" => "int(11)",
            "inputType" => "text",
            "disabledEdit" => "true"
        ]
    ];

    public $editCategories = [
        "Main" => [
            "WorkOrderNumber" => [
                "dbType" => "varchar(36)",
                "inputType" => "text",
                "disabledEdit" => "true",
                "disabledNew" => "true",
                "defaultValue" => ""
            ],
            "WorkOrderLineNumber" => [
                "dbType" => "int(11)",
                "inputType" => "text",
                "disabledEdit" => "true",
                "disabledNew" => "true",
                "defaultOverride" => true,
                "defaultValue" => "(new)",
                "autogenerated" => true
            ],
            "WorkOrderStartDate" => [
                "dbType" => "datetime",
                "inputType" => "datetime",
                "defaultValue" => "now"
            ],
            "WorkOrderExpectedDate" => [
                "dbType" => "datetime",
                "inputType" => "datetime",
                "defaultValue" => "now"
            ],
            "WorkOrderCompleted" => [
                "dbType" => "tinyint(1)",
                "inputType" => "checkbox",
                "defaultValue" => "0"
            ],
            "WorkOrderCompletedDate" => [
                "dbType" => "datetime",
                "inputType" => "datetime",
                "defaultValue" => "now"
            ],
            "WorkOrderBOMNumber" => [
                "dbType" => "varchar(36)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "WorkOrderBOMDescription" => [
                "dbType" => "varchar(120)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "WorkOrderBOMQuantity" => [
                "dbType" => "int(11)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "WorkOrderBOMUnitCost" => [
                "dbType" => "decimal(19,4)",
                "format" => "{0:n}",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "WorkOrderBOMUnitLabor" => [
                "dbType" => "decimal(19,4)",
                "format" => "{0:n}",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "WorkOrderBOMOtherCost" => [
                "dbType" => "decimal(19,4)",
                "format" => "{0:n}",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "WorkOrderTotalCost" => [
                "dbType" => "decimal(19,4)",
                "format" => "{0:n}",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "WorkOrderSerialNumber" => [
                "dbType" => "varchar(36)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "WorkOrderDescription" => [
                "dbType" => "varchar(255)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "WorkOrderStatus" => [
                "dbType" => "varchar(36)",
                "inputType" => "dropdown",
                "dataProvider" => "getWorkOrderStatus",
                "defaultValue" => ""
            ],
            "WorkOrderPriority" => [
                "dbType" => "varchar(36)",
                "inputType" => "dropdown",
                "dataProvider" => "getWorkOrderPriority",
                "defaultValue" => ""
            ],
            "WorkOrderInProgress" => [
                "dbType" => "varchar(36)",
                "inputType" => "dropdown",
                "dataProvider" => "getWorkOrderProgress",
                "defaultValue" => ""
            ],
            "WorkOrderProgressNotes" => [
                "dbType" => "varchar(255)",
                "inputType" => "text",
                "defaultValue" => ""
            ]
       ],
        "Memos" => [
            "WorkOrderDetailMemo1" => [
                "dbType" => "varchar(80)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "WorkOrderDetailMemo2" => [
                "dbType" => "varchar(80)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "WorkOrderDetailMemo3" => [
                "dbType" => "varchar(80)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "WorkOrderDetailMemo4" => [
                "dbType" => "varchar(80)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "WorkOrderDetailMemo5" => [
                "dbType" => "varchar(80)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "WorkOrderDetailMemo6" => [
                "dbType" => "varchar(80)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "WorkOrderDetailMemo7" => [
                "dbType" => "varchar(80)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "WorkOrderDetailMemo8" => [
                "dbType" => "varchar(80)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "WorkOrderDetailMemo9" => [
                "dbType" => "varchar(80)",
                "inputType" => "text",
                "defaultValue" => ""
            ]
        ],
        "Signature" => [
            "Signature" => [
                "dbType" => "varchar(36)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "SignaturePassword" => [
                "dbType" => "varchar(36)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "SupervisorSignature" => [
                "dbType" => "varchar(36)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "SupervisorSignaturePassword" => [
                "dbType" => "varchar(36)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "ManagerSignature" => [
                "dbType" => "varchar(36)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "ManagerSignaturePassword" => [
                "dbType" => "varchar(36)",
                "inputType" => "text",
                "defaultValue" => ""
            ]
        ],
        "Assembly Instructions" => [
            "WorkOrderNumber" => [
                "dbType" => "varchar(36)",
                "inputType" => "text",
                "disabledEdit" => "true"
            ],
            "WorkOrderLineNumber" => [
                "dbType" => "int(11)",
                "inputType" => "text",
                "disabledEdit" => "true"
            ]            
        ]
    ];
    public $columnNames = [
        "WorkOrderNumber" => "Order Number",
        "WorkOrderType" => "Type",
        "WorkOrderDate" => "Date",
        "WorkOrderStartDate" => "Start Date",
        "WorkOrderManager" => "Manager",
        "WorkOrderCompletedDate" => "Completed Date",
        "WorkOrderReference" => "Reference",
        "WorkOrderTotalCost" => "Total Cost",
        "WorkOrderExpectedDate" => "Expected Date",
        "WorkOrderCompleted" => "Completed",
        "WorkOrderCancelDate" => "Work Order Cancel Date",
        "WorkOrderReferenceDate" => "Work Order Reference Date",
        "WorkOrderRequestedBy" => "Work Order Requested By",
        "WorkOrderAssignedTo" => "Work Order Assigned To",
        "WorkOrderApprovedBy" => "Work Order Approved By",
        "WorkOrderApprovedByDate" => "Work Order Approved By Date",
        "WorkOrderForCompanyID" => "Work Order For Company ID",
        "WorkOrderForDivisionID" => "Work Order For Division ID",
        "WorkOrderForDepartmentID" => "Work Order For Department ID",
        "WorkOrderReason" => "Work Order Reason",
        "WorkOrderDescription" => "Work Order Description",
        "WorkOrderStatus" => "Work Order Status",
        "WorkOrderPriority" => "Work Order Priority",
        "WorkOrderInProgress" => "Work Order In Progress",
        "WorkOrderProgressNotes" => "Work Order Progress Notes",
        "WorkOrderDetailMemo1" => "Memo 1",
        "WorkOrderDetailMemo2" => "Memo 2",
        "WorkOrderDetailMemo3" => "Memo 3",
        "WorkOrderDetailMemo4" => "Memo 4",
        "WorkOrderDetailMemo5" => "Memo 5",
        "WorkOrderDetailMemo6" => "Memo 6",
        "WorkOrderDetailMemo7" => "Memo 7",
        "WorkOrderDetailMemo8" => "Memo 8",
        "WorkOrderDetailMemo9" => "Memo 9",
        "Signature" => "Signature",
        "SignaturePassword" => "Signature Password",
        "SupervisorSignature" => "Supervisor Signature",
        "SupervisorSignaturePassword" => "Supervisor Signature Password",
        "ManagerSignature" => "Manager Signature",
        "ManagerSignaturePassword" => "Manager Signature Password",
        "Memorize" => "Memorize",
		"WorkOrderLineNumber" => "Line Number",
		"WorkOrderBOMNumber" => "BOM Number",
		"WorkOrderBOMDescription" => "BOM Description",
		"WorkOrderBOMQuantity" => "BOM Quantity",
		"WorkOrderBOMUnitCost" => "BOM Unit Cost",
		"WorkOrderSerialNumber" => "Serial Number",
		"WorkOrderBOMOtherCost" => "BOM Other Cost",
		"WorkOrderBOMUnitLabor" => "BOM Unit Labor"
    ];
}?>
