<?php
/*
  Name of Page: Receipts Detail model

  Method: Model for Receipts Detail page It provides data from database and default values, column names and categories

  Date created: autogenerated

  Use: this model used by views/grivView.php for:
  - as a dictionary for view during building interface(tabs and them names, fields and them names etc, column name and corresponding translationid)
  - for loading data from tables, updating, inserting and deleting

  Input parameters:
  $db: database instance
  methods have their own parameters

  Output parameters:
  - dictionaries as public properties
  - methods have their own output

  Called from:
  created and used for ajax requests by grid controller
  used as model by views/www.integralaccountingx.com\NewTechPhp\app\Http\Models\EnterpriseASPAR\CashReceipts\ReceiptsHeaderList.php

  Calls:
  MySql Database

  Last Modified: 08/14/2017
  Last Modified by: Zaharov Nikita
*/

require "./models/gridDataSource.php";

class gridData extends gridDataSource{
    protected $tableName = "receiptsdetail";
    public $dashboardTitle ="Receipts Detail";
    public $breadCrumbTitle ="Receipts Detail";
    public $idField ="ReceiptID";
    public $idFields = ["CompanyID","DivisionID","DepartmentID","ReceiptID", "ReceiptDetailID"];
    public $gridFields = [
        "ReceiptID" => [
            "dbType" => "varchar(36)",
            "inputType" => "text"
        ],
        "ReceiptDetailID" => [
            "dbType" => "bigint(20)",
            "inputType" => "text"
        ], 
		"DocumentNumber" => [
			"dbType" => "varchar(36)",
			"inputType" => "text"
		],
		"DocumentDate" => [
			"dbType" => "datetime",
			"inputType" => "datetime"
		],
        "AppliedAmount" => [
            "dbType" => "decimal(19,4)",
            "format" => "{0:n}",
            "inputType" => "text"
        ],
		"ProjectID" => [
			"dbType" => "varchar(36)",
			"inputType" => "text"
		],
        "Amount" => [
            "dbType" => "decimal(19,4)",
            "format" => "{0:n}",
            "inputType" => "text"
        ],
    ];

    public $editCategories = [
        "Main" => [
            "ReceiptID" => [
                "dbType" => "varchar(36)",
                "inputType" => "text",
                "disabledEdit" => "true",
                "disabledNew" => "true",
            ],
            "ReceiptDetailID" => [
                "dbType" => "bigint(20)",
                "inputType" => "text",
                "disabledEdit" => "true",
                "disabledNew" => "true",
                "autogenerated" => "true",
                "defaultValue" => "-1"
            ], 
            "DocumentNumber" => [
                "dbType" => "varchar(36)",
                "inputType" => "text"
            ],
            "DocumentDate" => [
                "dbType" => "datetime",
                "inputType" => "datetime"
            ],
            "AppliedAmount" => [
                "dbType" => "decimal(19,4)",
                "format" => "{0:n}",
                "inputType" => "text"
            ],
            "ProjectID" => [
                "dbType" => "varchar(36)",
                "inputType" => "dropdown",
                "dataProvider" => "getProjects"
            ]
        ],
        "Memos" => [
            "DetailMemo1" => [
                "dbType" => "varchar(50)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "DetailMemo2" => [
                "dbType" => "varchar(50)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "DetailMemo3" => [
                "dbType" => "varchar(50)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "DetailMemo4" => [
                "dbType" => "varchar(50)",
                "inputType" => "text",
                "defaultValue" => ""
            ],
            "DetailMemo5" => [
                "dbType" => "varchar(50)",
                "inputType" => "text",
                "defaultValue" => ""
            ]
        ]
    ];

    public $columnNames = [
        "ReceiptID" => "Receipt ID",
        "ReceiptTypeID" => "Receipt Type",
        "CustomerID" => "Customer ID",
        "TransactionDate" => "Transaction Date",
        "CurrencyID" => "Currency ID",
        "Amount" => "Amount",
        "Status" => "Status",
        "Deposited" => "Deposited",
        "Cleared" => "Cleared",
        "Reconciled" => "Reconciled",
        "Posted" => "Posted",
        "ReceiptClassID" => "Receipt Class ID",
        "CheckNumber" => "Check Number",
        "Memorize" => "Memorize",
        "SystemDate" => "System Date",
        "DueToDate" => "Due To Date",
        "OrderDate" => "Order Date",
        "CurrencyExchangeRate" => "Currency Exchange Rate",
        "UnAppliedAmount" => "UnApplied Amount",
        "GLBankAccount" => "GL Bank Account",
        "NSF" => "NSF",
        "Notes" => "Notes",
        "CreditAmount" => "Credit Amount",
        "DetailMemo1" => "Memo 1",
        "DetailMemo2" => "Memo 2",
        "DetailMemo3" => "Memo 3",
        "DetailMemo4" => "Memo 4",
        "DetailMemo5" => "Memo 5",
        "DetailMemo6" => "Memo 6",
        "DetailMemo7" => "Memo 7",
        "DetailMemo8" => "Memo 8",
        "DetailMemo9" => "Memo 9",
 		"DocumentNumber" => "Doc Number",
		"DocumentDate" => "Doc Date",
        "AppliedAmount" => "Amount",
		"ProjectID" => "ProjectID"
    ];
}
?>
