* Overview
  For ALL API requests we using GET and POST HTTP methods.
  For body we using JSON encoding. 
  You can use any language which can send the GET and POST HTTP requests.
  Any request to API start from base of URL - /EnterpriseUniversalAPI/index.php?page=api&module=modulename
  Where:
  - EnterpriseUniversalAPI can be changed to any other name, if you'll change folder of project.
  - modulename is name of module for using. For example, we have following modules:
    + auth
      for login, session control etc
    + forms
      for working with all records in system. It's all CRUD operations and actions
    + language
      for changing language
    + etc

  Each module can have own paths(for some submodules) and actions.
  A common API using scenario:
  - request for login and getting session_id
  - request for
    + get record or records
    + insert record
    + update record
    + delete record
    + execute some action(in most cases Action is sql stored procedure or analog, implemented inside API server)
      
  Example:
  - request for login and getting session_id
    Request URL: /EnterpriseUniversalAPI/index.php?page=api&module=auth&action=login
    Request Method: POST
    Request JSON Body:
    {
      CompanyID : "DINOS",
      DivisionID : "DEFAULT",
      DepartmentID : "DEFAULT",
      EmployeeID : "Demo",
      EmployeePassword : "Demo",
      language : "english"
    }
    JSON Response:
    {
      session_id : "session number"
    }
    or
    401 status if credentials wrong
 
  - request to get list of Orders
    If request success, then data will be array of the order records.
    Request URL: /EnterpriseUniversalAPI/index.php?page=api&module=forms&path=AccountsReceivable/OrderProcessing/ViewOrders&action=list&session_id=session_number
    Request Method: GET
    JSON Response:
    [ ... ] - array of order objects
    401 status if credentials wrong

* Modules and their API
** auth
** forms
