<?php
class permissionsByFile{
public $permissions = [
    "APTransactionTypes" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ARTransactionTypes" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "AccessPermissions" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "EMEdit|ADSetup",
        "insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "AuditLogin" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "AuditLoginHistory" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "AuditTablesDescription" => [
        "select" => "AuditView|ADView|ADSetup",
        "update" => "AuditEdit|ADSetup",
        "insert" => "AuditAdd|ADSetup",
        "delete" => "AuditDelete|ADSetup",
    ],
    "AuditTrail" => [
        "select" => "AuditView|ADView|ADSetup",
        "update" => "AuditEdit|ADSetup",
        "insert" => "AuditAdd|ADSetup",
        "delete" => "AuditDelete|ADSetup",
    ],
    "AuditTrailHistory" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "BankAccounts" => [
        "select" => "GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "BankAccountsContacts" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "BankReconciliation" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "GLEdit|ADSetup",
        "insert" => "GLAdd|ADSetup",
        "delete" => "GLDelete|ADSetup",
    ],
    "BankReconciliationSummary" => [
        "select" => "GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "BankTransactionTypes" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "BankTransactions" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "GLEdit|ADSetup",
        "insert" => "GLAdd|ADSetup",
        "delete" => "GLDelete|ADSetup",
    ],
    "CashReceiptCustomer" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "CashReceiptInvoice" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "CashReceiptsHeader" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "CashReceipts" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "CommentTypes" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "Companies" => [
        "select" => "ARView|APView|GLView|OEView|ADView|ADSetup",
        "update" => "ARView|ADSetup",
        "insert" => "ARView|ADSetup",
        "delete" => "any",
    ],
    "CompaniesChallanges" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "CompaniesDisplayLang" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "CompaniesNextNumbers" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "CompaniesSystemWideMessage" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "CompaniesWorkFlowTypes" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "CompaniesWorkflowByEmployees" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ContactIndustry" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ContactRegions" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ContactSource" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ContactType" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ContractTrackingHeader" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ContractTypes" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ContractsHeader" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "OEEdit|ADSetup",
        "insert" => "OEAdd|ADSetup",
        "delete" => "OEDelete|ADSetup",
    ],
    "CreditCardTypes" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "CreditMemoHeader" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "CreditMemo" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "CreditMemoHistory" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "CreditMemoHeaderClosed" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "CreditMemoHeaderHistory" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "CreditMemoHeaderMemorized" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "CreditMemoIssuePayments" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "CurrencyTypes" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "CurrencyTypesHistory" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "CustomerAccountStatuses" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "CustomerComments" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "CustomerContactLog" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "CustomerContacts" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "CustomerCreditReferences" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "CustomerFinancials" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "CustomerInformation" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "CustomerInformationLookup" => [
        "select" => "Always",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "CustomerItemCrossReference" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "CustomerPriceCrossReference" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "CustomerReferences" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "CustomerSatisfaction" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "CustomerShipForLocations" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "CustomerShipToLocations" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "CustomerTypes" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "DebitMemoHeader" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "POEdit|ADSetup",
        "insert" => "POAdd|ADSetup",
        "delete" => "PODelete|ADSetup",
    ],
    "DebitMemo" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "POEdit|ADSetup",
        "insert" => "POAdd|ADSetup",
        "delete" => "PODelete|ADSetup",
    ],
    "DebitMemoHeaderApplyToPayment" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "DebitMemoHeaderApplyToPayments" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "DebitMemoHeaderClosed" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "DebitMemoHeaderHistory" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "DebitMemoHistory" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "DebitMemoHeaderMemorized" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "POEdit|ADSetup",
        "insert" => "POAdd|ADSetup",
        "delete" => "PODelete|ADSetup",
    ],
    "DebitMemoHeaderPayments" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "APEdit|ADSetup",
        "insert" => "any",
        "delete" => "any",
    ],
    "Departments" => [
        "select" => "ARView|APView|GLView|OEView|ADView|ADSetup",
        "update" => "ADSetup",
        "insert" => "ADSetup",
        "delete" => "any",
    ],
    "Divisions" => [
        "select" => "ARView|APView|GLView|OEView|ADView|ADSetup",
        "update" => "ADSetup",
        "insert" => "ADSetup",
        "delete" => "any",
    ],
    "EDIDirection" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "EDIDocumentTypes" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "EDIExceptionTypes" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "EDIExceptions" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "EDISetup" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "EDIAddresses" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "EDIStatements" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "EDIStatementsHistory" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "EDIOrderHeader" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "EDIOrder" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "EDIInvoiceHeader" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "EDIInvoice" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "EDIReceiptsHeader" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "EDIReceipts" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "EDIPurchaseHeader" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "EDIPurchase" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "EDIPaymentsHeader" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "EDIPayments" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "EDIItems" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ErrorLog" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ExpenseReportHeader" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ExpenseReport" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ExpenseReportHistory" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ExpenseReportHeaderHistory" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ExpenseReportItems" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ExpenseReportReasons" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ExpenseReportTypes" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "FixedAssetDepreciationMethods" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "FixedAssetStatus" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "FixedAssetType" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "FixedAssets" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "GLEdit|ADSetup",
        "insert" => "GLAdd|ADSetup",
        "delete" => "GLDelete|ADSetup",
    ],
    "GLParentSegment" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "GenericReport" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "HelpMessageBoard" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "HelpMessageHeading" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "HelpMessageTopic" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "HelpNewsBoard" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "HelpPriority" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "HelpProblemReport" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "HelpProblemType" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "HelpReleaseDates" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "HelpRequestMethod" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "HelpResourceType" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "HelpResources" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "HelpSeverity" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "HelpStatus" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "HelpSupportRequest" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "HelpSupportRequestType" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InventoryAdjustmentTypes" => [
        "select" => "APView|ARView|GLView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "InventoryAdjustments" => [
        "select" => "APView|ARView|GLView|ADView|ADSetup",
        "update" => "APEdit|AREdit|GLEdit|ADSetup",
        "insert" => "APAdd|ARAdd|GLAdd|ADSetup",
        "delete" => "APDelete|ARDelete|GLDelete|ADSetup",
    ],
    "InventoryAssemblies" => [
        "select" => "APView|ARView|GLView|ADView|ADSetup",
        "update" => "APEdit|AREdit|GLEdit|ADSetup",
        "insert" => "APAdd|ARAdd|GLAdd|ADSetup",
        "delete" => "APDelete|ARDelete|GLDelete|ADSetup",
    ],
    "InventoryAssembliesInstructions" => [
        "select" => "APView|ARView|GLView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "InventoryAssembliesLookup" => [
        "select" => "Always",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InventoryByWarehouse" => [
        "select" => "APView|ARView|GLView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "InventoryByWarehouseLookup" => [
        "select" => "Always",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InventoryCart" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InventoryCategories" => [
        "select" => "APView|ARView|GLView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "InventoryCategoriesDisplayLang" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InventoryCreateAssembly" => [
        "select" => "APView|ARView|GLView|ADView|ADSetup",
        "update" => "APEdit|AREdit|ADSetup",
        "insert" => "any",
        "delete" => "any",
    ],
    "InventoryCrossSelling" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InventoryFamilies" => [
        "select" => "APView|ARView|GLView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "InventoryFamiliesDisplayLang" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InventoryItemTypes" => [
        "select" => "APView|ARView|GLView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "InventoryItems" => [
        "select" => "APView|ARView|GLView|ADView|ADSetup",
        "update" => "APEdit|AREdit|GLEdit|ADSetup",
        "insert" => "APAdd|ARAdd|GLAdd|ADSetup",
        "delete" => "APDelete|ARDelete|GLDelete|ADSetup",
    ],
    "InventoryItemsDisplayLang" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InventoryItemsLookup" => [
        "select" => "Always",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InventoryNoticifations" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InventoryPricingCode" => [
        "select" => "APView|ARView|GLView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "InventoryPricingMethods" => [
        "select" => "APView|ARView|GLView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "InventoryRelations" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InventoryReviews" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InventorySerialNumbers" => [
        "select" => "APView|ARView|GLView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "InventorySubstitutions" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InventoryTransfer" => [
        "select" => "APView|ARView|GLView|ADView|ADSetup",
        "update" => "APEdit|AREdit|GLEdit|ADSetup",
        "insert" => "APAdd|ARAdd|GLAdd|ADSetup",
        "delete" => "APDelete|ARDelete|GLDelete|ADSetup",
    ],
    "InventoryWish" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InventoryWishList" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InventoryWorkOrderHeader" => [
        "select" => "WOView|ADView|ADSetup",
        "update" => "WOEdit|ADSetup",
        "insert" => "WOAdd|ADSetup",
        "delete" => "WODelete|ADSetup",
    ],
    "InventoryWorkOrder" => [
        "select" => "WOView|ADView|ADSetup",
        "update" => "WOEdit|ADSetup",
        "insert" => "WOAdd|ADSetup",
        "delete" => "WODelete|ADSetup",
    ],
    "InventoryWorkOrderHistory" => [
        "select" => "WOView|ADView|ADSetup",
        "update" => "WOEdit|ADSetup",
        "insert" => "WOAdd|ADSetup",
        "delete" => "WODelete|ADSetup",
    ],
    "InventoryWorkOrderHeaderClosed" => [
        "select" => "WOView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InventoryWorkOrderHeaderHistory" => [
        "select" => "WOView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InventoryWorkOrderHeaderMemorized" => [
        "select" => "WOView|ADView|ADSetup",
        "update" => "WOEdit|ADSetup",
        "insert" => "WOAdd|ADSetup",
        "delete" => "WODelete|ADSetup",
    ],
    "InvoiceHeader" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "PositivePay" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "Invoice" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "InvoiceHistory" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "InvoiceHeaderClosed" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InvoiceHeaderHistory" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InvoiceHeaderMemorized" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "InvoiceTrackingHeader" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "InvoiceTracking" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "JointPaymentsHeader" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "APEdit|ADSetup",
        "insert" => "APAdd|ADSetup",
        "delete" => "APDelete|ADSetup",
    ],
    "JointPaymentsHeaderApprove" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "JointPaymentsHeaderIssue" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "JointVendorInformation" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "JointVendorInformationLookup" => [
        "select" => "Always",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "LeadComments" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "LeadContacts" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "LeadInformation" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "LeadInformationLookup" => [
        "select" => "Always",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "LeadSatisfaction" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "LeadType" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ControlNumbers" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "GLEdit|ADSetup",
        "insert" => "GLAdd|ADSetup",
        "delete" => "GLDelete|ADSetup",
    ],
    "OFXImport" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "GLEdit|ADSetup",
        "insert" => "GLAdd|ADSetup",
        "delete" => "GLDelete|ADSetup",
    ],
    "LedgerAccountGroup" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "GLEdit|ADSetup",
        "insert" => "GLAdd|ADSetup",
        "delete" => "GLDelete|ADSetup",
    ],
    "LedgerAccountSubGroup" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "GLEdit|ADSetup",
        "insert" => "GLAdd|ADSetup",
        "delete" => "GLDelete|ADSetup",
    ],
    "LedgerAccountTypes" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "LedgerBalanceType" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "LedgerChartOfAccounts" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "GLEdit|ADSetup",
        "insert" => "GLAdd|ADSetup",
        "delete" => "GLDelete|ADSetup",
    ],
    "LedgerStoredChartOfAccounts" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "GLEdit|ADSetup",
        "insert" => "GLAdd|ADSetup",
        "delete" => "ADSetup",
    ],
    "LedgerStoredAccounts" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "GLEdit|ADSetup",
        "insert" => "GLAdd|ADSetup",
        "delete" => "ADSetup",
    ],
    "LedgerChartOfAccountsBudgets" => [
        "select" => "GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "LedgerChartOfAccountsPriorYears" => [
        "select" => "GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "LedgerParentSegment" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "LedgerParentSegmentMaster" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "GLEdit|ADSetup",
        "insert" => "GLAdd|ADSetup",
        "delete" => "GLDelete|ADSetup",
    ],
    "LedgerPeriodClose" => [
        "select" => "ARView|APView|GLView|OEView|ADView|ADSetup",
        "update" => "ARView|ADSetup",
        "insert" => "ARView|ADSetup",
        "delete" => "any",
    ],
    "LedgerSubAccountGroup" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "GLEdit|ADSetup",
        "insert" => "GLAdd|ADSetup",
        "delete" => "GLDelete|ADSetup",
    ],
    "LedgerTransactionTypes" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "LedgerTransactions" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "GLEdit|ADSetup",
        "insert" => "GLAdd|ADSetup",
        "delete" => "GLDelete|ADSetup",
    ],
    "LedgerBankDeposits" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "GLEdit|ADSetup",
        "insert" => "GLAdd|ADSetup",
        "delete" => "GLDelete|ADSetup",
    ],
    "LedgerAccountsTransactions" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "GLEdit|ADSetup",
        "insert" => "GLAdd|ADSetup",
        "delete" => "GLDelete|ADSetup",
    ],
    "LedgerAccountTransactions" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "GLEdit|ADSetup",
        "insert" => "GLAdd|ADSetup",
        "delete" => "GLDelete|ADSetup",
    ],
    "LedgerTransactionsClosed" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "LedgerTransactionsHistory" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "LedgerTransactionsMemorized" => [
        "select" => "GLView|ADView|ADSetup",
        "update" => "GLEdit|ADSetup",
        "insert" => "GLAdd|ADSetup",
        "delete" => "GLDelete|ADSetup",
    ],
    "LedgerYearClose" => [
        "select" => "ARView|APView|GLView|OEView|ADView|ADSetup",
        "update" => "ARView|ADSetup",
        "insert" => "ARView|ADSetup",
        "delete" => "any",
    ],
    "OrderHeader" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "OEEdit|ADSetup",
        "insert" => "OEAdd|ADSetup",
        "delete" => "OEDelete|ADSetup",
    ],
    "OrderHeaderMemorized" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "OEEdit|ADSetup",
        "insert" => "OEAdd|ADSetup",
        "delete" => "OEDelete|ADSetup",
    ],
    "Order" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "OEEdit|ADSetup",
        "insert" => "OEAdd|ADSetup",
        "delete" => "OEDelete|ADSetup",
    ],
    "OrderHistory" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "OEEdit|ADSetup",
        "insert" => "OEAdd|ADSetup",
        "delete" => "OEDelete|ADSetup",
    ],
    "OrderHeaderBack" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "OEEdit|ADSetup",
        "insert" => "OEAdd|ADSetup",
        "delete" => "OEDelete|ADSetup",
    ],
    "OrderHeaderClosed" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "OrderHeaderHistory" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "OrderHeaderHold" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "OEEdit|ADSetup",
        "insert" => "OEAdd|ADSetup",
        "delete" => "OEDelete|ADSetup",
    ],
    "OrderHeaderInvoice" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "OrderHeaderPick" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "OrderHeaderShip" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "OEEdit|ADSetup",
        "insert" => "OEAdd|ADSetup",
        "delete" => "OEDelete|ADSetup",
    ],
    "OrderHeaderShipStep2" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "OEEdit|ADSetup",
        "insert" => "OEAdd|ADSetup",
        "delete" => "OEDelete|ADSetup",
    ],
    "OrderTrackingHeader" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "OrderTracking" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "OrderTypes" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "POSSetup" => [
        "select" => "ADView|ADSetup",
        "update" => "AuditView|ADSetup",
        "insert" => "ADSetup",
        "delete" => "AuditView|ADSetup",
    ],
    "PaymentClasses" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PaymentMethods" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PaymentTypes" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PaymentsHeader" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "APEdit|ADSetup",
        "insert" => "APAdd|ADSetup",
        "delete" => "APDelete|ADSetup",
    ],
    "Payments" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "APEdit|ADSetup",
        "insert" => "APAdd|ADSetup",
        "delete" => "APDelete|ADSetup",
    ],
    "PaymentsHeaderApprove" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PaymentsHeaderClosed" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PaymentsHeaderHistory" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PaymentsHistory" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PaymentsHeaderIssue" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "APEdit|ADSetup",
        "insert" => "APAdd|ADSetup",
        "delete" => "APDelete|ADSetup",
    ],
    "PaymentsHeaderIssueCreditMemo" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "APEdit|ADSetup",
        "insert" => "APAdd|ADSetup",
        "delete" => "APDelete|ADSetup",
    ],
    "PaymentsHeaderMemorized" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "APEdit|ADSetup",
        "insert" => "APAdd|ADSetup",
        "delete" => "APDelete|ADSetup",
    ],
    "PaymentsHeaderVoid" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "APEdit|ADSetup",
        "insert" => "APAdd|ADSetup",
        "delete" => "APDelete|ADSetup",
    ],
    "PaymentsHeaderVoidHistory" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PaymentsMatching" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "APEdit|ADSetup",
        "insert" => "APAdd|ADSetup",
        "delete" => "APDelete|ADSetup",
    ],
    "PayrollCheckType" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollChecks" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollCityTax" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollCityTaxTables" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollCommision" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "PayrollCountyTax" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollCountyTaxTables" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollEmailMessages" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollEmployeeDepartment" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "PayrollEmployeeEmailMessage" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "EMEdit|ADSetup",
        "insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "PayrollEmployeeInstantMessage" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "EMEdit|ADSetup",
        "insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "PayrollEmployeePayFrequency" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "EMEdit|ADSetup",
        "insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "PayrollEmployeePayType" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "EMEdit|ADSetup",
        "insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "PayrollEmployeeStatus" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "EMEdit|ADSetup",
        "insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "PayrollEmployeeStatusType" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "EMEdit|ADSetup",
        "insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "PayrollEmployeeType" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "EMEdit|ADSetup",
        "insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "PayrollEmployees" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollEmployeesAccrual" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "EMEdit|ADSetup",
        "insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "PayrollEmployeesAccrualFrequency" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "EMEdit|ADSetup",
        "insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "PayrollEmployeesAccrualTypes" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "EMEdit|ADSetup",
        "insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "PayrollEmployeesCalendar" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "EMEdit|ADSetup",
        "insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "PayrollEmployeesCurrentlyOn" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "EMEdit|ADSetup",
        "insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "PayrollEmployeesEventTypes" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "EMEdit|ADSetup",
        "insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "PayrollEmployeesEvents" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "EMEdit|ADSetup",
        "insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "PayrollEmployeesTaskDetail" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PayrollEmployeesTaskHeader" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        //"update" => "EMEdit|ADSetup",
        //"insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "PayrollEmployeesTaskPriority" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "EMEdit|ADSetup",
        "insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "PayrollEmployeesTaskType" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "EMEdit|ADSetup",
        "insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "PayrollEmployeesTimesheetHeader" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "EMEdit|ADSetup",
        "insert" => "EMAdd|ADSetup",
        "delete" => "EMDelete|ADSetup",
    ],
    "PayrollFedTax" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollFedTaxTables" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollInstantMessages" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollItemBasis" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollItemTypes" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollItems" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollItemsMaster" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollPayEmployeeManual" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollPayEmployees" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "PayrollRegister" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollRegisterCheck" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "PayrollRegisterDetail" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PayrollRegisterDetailHistory" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PayrollRegisterHistory" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PayrollSetup" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollStateTax" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollStateTaxTables" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollW2Detail" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollW3Detail" => [
        "select" => "PRView|EMView|ADView|ADSetup",
        "update" => "PREdit|ADSetup",
        "insert" => "PRAdd|ADSetup",
        "delete" => "PRDelete|ADSetup",
    ],
    "PayrollWithholdings" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PayrollWithholdingsState" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ProjectTypes" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "Projects" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "PurchaseContractHeader" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PurchaseContractHeaderHistory" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PurchaseContractLedger" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PurchaseContractLedgerHistory" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PurchaseHeader" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "POEdit|ADSetup",
        "insert" => "POAdd|ADSetup",
        "delete" => "PODelete|ADSetup",
    ],
    "Purchase" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "POEdit|ADSetup",
        "insert" => "POAdd|ADSetup",
        "delete" => "PODelete|ADSetup",
    ],
    "PurchaseReceive" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "POEdit|ADSetup",
        "insert" => "POAdd|ADSetup",
        "delete" => "PODelete|ADSetup",
    ],
    "PurchaseHeaderApprove" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "APEdit|ADSetup",
        "insert" => "any",
        "delete" => "any",
    ],
    "PurchaseHeaderClosed" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PurchaseHeaderHistory" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PurchaseHeaderMemorized" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "POEdit|ADSetup",
        "insert" => "POAdd|ADSetup",
        "delete" => "PODelete|ADSetup",
    ],
    "PurchaseHeaderReceive" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "POEdit|ADSetup",
        "insert" => "any",
        "delete" => "any",
    ],
    "PurchaseHeaderReceived" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "POEdit|ADSetup",
        "insert" => "any",
        "delete" => "any",
    ],
    "PurchaseReceiptHeader" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PurchaseReceiptHeaderHistory" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PurchaseTrackingHeader" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "PurchaseTracking" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "QuoteHeader" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "OEEdit|ADSetup",
        "insert" => "OEAdd|ADSetup",
        "delete" => "OEDelete|ADSetup",
    ],
    "QuoteHeaderMemorized" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "OEEdit|ADSetup",
        "insert" => "OEAdd|ADSetup",
        "delete" => "OEDelete|ADSetup",
    ],
    "Quote" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "OEEdit|ADSetup",
        "insert" => "OEAdd|ADSetup",
        "delete" => "OEDelete|ADSetup",
    ],
    "QuoteTrackingHeader" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "QuoteTypes" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "RMAHeader" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "RMA" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "RMAHeaderApprove" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "RMAHeaderClosed" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "RMAHeaderHistory" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "RMAHeaderMemorized" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "RMAHeaderReceive" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "any",
        "delete" => "any",
    ],
    "RMAHeaderReceived" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ReceiptClass" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ReceiptMethods" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ReceiptTypes" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ReceiptsHeader" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "Receipts" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "ReceiptsHeaderClosed" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ReceiptsHeaderHistory" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ReceiptsHeaderMemorized" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "ReturnCashReceiptInvoice" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "ReturnCashReceiptVendor" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "APEdit|ADSetup",
        "insert" => "any",
        "delete" => "any",
    ],
    "ReturnCashReceiptsHeader" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "ReturnHeader" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "POEdit|ADSetup",
        "insert" => "POAdd|ADSetup",
        "delete" => "PODelete|ADSetup",
    ],
    "Return" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "POEdit|ADSetup",
        "insert" => "POAdd|ADSetup",
        "delete" => "PODelete|ADSetup",
    ],
    "ReturnHeaderInvoice" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ReturnHeaderMemorized" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "POEdit|ADSetup",
        "insert" => "POAdd|ADSetup",
        "delete" => "PODelete|ADSetup",
    ],
    "ReturnHeaderPick" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ReturnHeaderShip" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ReturnInvoiceHeader" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "APEdit|ADSetup",
        "insert" => "APAdd|ADSetup",
        "delete" => "APDelete|ADSetup",
    ],
    "ReturnInvoice" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "APEdit|ADSetup",
        "insert" => "APAdd|ADSetup",
        "delete" => "APDelete|ADSetup",
    ],
    "ReturnInvoiceHeaderClosed" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ReturnInvoiceHeaderHistory" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ReturnInvoiceHeaderMemorized" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "APEdit|ADSetup",
        "insert" => "APAdd|ADSetup",
        "delete" => "APDelete|ADSetup",
    ],
    "ReturnInvoiceHeaderShipped" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ReturnReceiptsHeader" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "APEdit|ADSetup",
        "insert" => "APAdd|ADSetup",
        "delete" => "APDelete|ADSetup",
    ],
    "SalesGroup" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ServiceInventoryItemsLookup" => [
        "select" => "Always",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ServiceInvoiceHeader" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "ServiceInvoiceHeaderClosed" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ServiceInvoiceHeaderHistory" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ServiceInvoiceHeaderMemorized" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "AREdit|ADSetup",
        "insert" => "ARAdd|ADSetup",
        "delete" => "ARDelete|ADSetup",
    ],
    "ServiceOrderHeader" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "OEEdit|ADSetup",
        "insert" => "OEAdd|ADSetup",
        "delete" => "OEDelete|ADSetup",
    ],
    "ServiceOrderHeaderClosed" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ServiceOrderHeaderHistory" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ServiceOrderHeaderHold" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "OEEdit|ADSetup",
        "insert" => "OEAdd|ADSetup",
        "delete" => "OEDelete|ADSetup",
    ],
    "ServiceOrderHeaderInvoice" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ServiceOrderHeaderMemorized" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "OEEdit|ADSetup",
        "insert" => "OEAdd|ADSetup",
        "delete" => "OEDelete|ADSetup",
    ],
    "ServiceOrderHeaderPick" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ServiceOrderHeaderShip" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "ShipmentMethods" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "SubAccount" => [
        "select" => "ARView|GLView|OEView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "TaxGroupDetail" => [
        "select" => "ARView|APView|GLView|OEView|ADView|ADSetup",
        "update" => "ADSetup",
        "insert" => "ADSetup",
        "delete" => "ADSetup",
    ],
    "TaxGroups" => [
        "select" => "ARView|APView|GLView|OEView|ADView|ADSetup",
        "update" => "ADSetup",
        "insert" => "ADSetup",
        "delete" => "ADSetup",
    ],
    "Taxes" => [
        "select" => "ARView|APView|GLView|OEView|ADView|ADSetup",
        "update" => "ADSetup",
        "insert" => "ADSetup",
        "delete" => "ADSetup",
    ],
    "Unlock" => [
        "select" => "ARView|APView|GLView|OEView|ADView|ADSetup",
        "update" => "ADSetup",
        "insert" => "ADSetup",
        "delete" => "ADSetup",
    ],
    "Terms" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "TimeUnits" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "Translation" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "VendorAccountStatuses" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "VendorComments" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "VendorContacts" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "VendorFinancials" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "APEdit|GLEdit|POEdit|ADSetup",
        "insert" => "any",
        "delete" => "any",
    ],
    "VendorInformation" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "APEdit|ADSetup",
        "insert" => "APAdd|ADSetup",
        "delete" => "APDelete|ADSetup",
    ],
    "VendorInformationLookup" => [
        "select" => "Always",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "VendorItemCrossReference" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "VendorPriceCrossReference" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "VendorTypes" => [
        "select" => "APView|GLView|POView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "WarehouseBinTypes" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "WarehouseBinZones" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "WarehouseBins" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "WarehouseTransitDetailHistory" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "WarehouseTransit" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "WarehouseTransitHistory" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "WarehouseTransitHeader" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "WarehouseTransitHeaderHistory" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "Warehouses" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "WarehousesContacts" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "WorkOrderHeaderInventoryHistory" => [
        "select" => "any",
        "update" => "any",
        "insert" => "any",
        "delete" => "any",
    ],
    "WorkOrderInProgress" => [
        "select" => "APView|ARView|GLView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "WorkOrderPriority" => [
        "select" => "APView|ARView|GLView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "WorkOrderStatus" => [
        "select" => "APView|ARView|GLView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ],
    "WorkOrderTypes" => [
        "select" => "APView|ARView|GLView|ADView|ADSetup",
        "update" => "Always",
        "insert" => "Always",
        "delete" => "Always",
    ]
];
}
?>